#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("MovieRenderPipelineDataTypes.h")]
///<summary>Contains information about the to-disk output generated by a movie pipeline. This structure is used both for per-shot work finished</summary>
public partial struct FMoviePipelineOutputData {
// MoviePipelineOutputData
	public UMoviePipeline Pipeline;
	public UMoviePipelineExecutorJob Job;
	public bool bSuccess;
	public TArray<FMoviePipelineShotOutputData> ShotData;
}
