#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("MoviePipelineOutputBase.h")]
///<summary>A base class for different output containers for the data generated by the Movie Pipeline,</summary>
public partial class UMoviePipelineOutputBase : UMoviePipelineSetting {
// MoviePipelineOutputBase
}
