#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>A base class for different output containers for the data generated by the Movie Pipeline,</summary>
[CppInclude("MoviePipelineOutputBase.h")]
public partial class UMoviePipelineOutputBase : UMoviePipelineSetting {
}
