namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>A base class for different output containers for the data generated by the Movie Pipeline,</summary>
[CppInclude("MoviePipelineOutputBase.h")]
public partial class UMoviePipelineOutputBase : UMoviePipelineSetting {
	public static UClass StaticClass() {return default;}
}
