namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Formats/JSON500/DisplayClusterConfigurationJsonTypes_500.h")]
public partial struct FDisplayClusterConfigurationJsonClusterSync_500 {
	public FDisplayClusterConfigurationJsonClusterSyncPolicy_500 RenderSyncPolicy;
	public FDisplayClusterConfigurationJsonClusterSyncPolicy_500 InputSyncPolicy;
}
