#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("UObject/NoExportTypes.h")]
///<summary>A set of numerical unit types supported by the engine. Mirrored from UnitConversion.h</summary>
public enum EUnit {
	Micrometers=0,
	Millimeters=1,
	Centimeters=2,
	Meters=3,
	Kilometers=4,
	Inches=5,
	Feet=6,
	Yards=7,
	Miles=8,
	Lightyears=9,
	Degrees=10,
	Radians=11,
	CentimetersPerSecond=12,
	MetersPerSecond=13,
	KilometersPerHour=14,
	MilesPerHour=15,
	Celsius=16,
	Farenheit=17,
	Kelvin=18,
	Micrograms=19,
	Milligrams=20,
	Grams=21,
	Kilograms=22,
	MetricTons=23,
	Ounces=24,
	Pounds=25,
	Stones=26,
	Newtons=27,
	PoundsForce=28,
	KilogramsForce=29,
	Hertz=30,
	Kilohertz=31,
	Megahertz=32,
	Gigahertz=33,
	RevolutionsPerMinute=34,
	Bytes=35,
	Kilobytes=36,
	Megabytes=37,
	Gigabytes=38,
	Terabytes=39,
	Lumens=40,
	Milliseconds=41,
	Seconds=42,
	Minutes=43,
	Hours=44,
	Days=45,
	Months=46,
	Years=47,
	Multiplier=48,
	Percentage=49,
	Unspecified=50,
}
