namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_ICVFX.h")]
public partial struct FDisplayClusterConfigurationICVFX_ViewportOCIO {
	public FDisplayClusterConfigurationOCIOConfiguration AllViewportsOCIOConfiguration;
	public TArray<FDisplayClusterConfigurationOCIOProfile> PerViewportOCIOProfiles;
}
