namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_ICVFX.h")]
public partial struct FDisplayClusterConfigurationICVFX_ChromakeySettings {
	public bool bEnable;
	public EDisplayClusterConfigurationICVFX_ChromakeyType ChromakeyType;
	public EDisplayClusterConfigurationICVFX_ChromakeySettingsSource ChromakeySettingsSource;
	public FLinearColor ChromakeyColor;
	public FDisplayClusterConfigurationICVFX_ChromakeyRenderSettings ChromakeyRenderTexture;
	public FDisplayClusterConfigurationICVFX_ChromakeyMarkers ChromakeyMarkers;
}
