namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_ICVFX.h")]
public partial struct FDisplayClusterConfigurationICVFX_LightcardOCIO {
	public EDisplayClusterConfigurationViewportLightcardOCIOMode LightcardOCIOMode;
	public FDisplayClusterConfigurationICVFX_LightcardCustomOCIO CustomOCIO;
}
