#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("AdjustSettings.h")]
public partial class UAdjustSettings : UAnalyticsSettingsBase {
	///<summary>Check to run in sandbox mode instead of production for non-distribution builds</summary>
	public bool bSandboxNondistribution;
	///<summary>Check to run in sandbox mode instead of production for distribution builds</summary>
	public bool bSandboxDistribution;
	///<summary>Application token from dashboard</summary>
	public string AppToken;
	///<summary>Level of verbosity to use for logging</summary>
	public EAndroidAdjustLogging LogLevel;
	///<summary>Token from dashboard for tracker URL (may be left empty)</summary>
	public string DefaultTracker;
	///<summary>Override the process name; will use the package name if not provided</summary>
	public string ProcessName;
	///<summary>Optional event buffering (send in batches once a minute instead of immediately)</summary>
	public bool bEventBuffering;
	///<summary>Send while in application in background</summary>
	public bool bSendInBackground;
	///<summary>Optional start delay (up to 10 seconds) before first events are sent</summary>
	public float DelayStart;
	///<summary>Mapping of event names to tokens generated by Adjust dashboard.</summary>
	public TArray<FAdjustEventMapping> EventMap;
}
