#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("GameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags.h")]
public partial class UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags : UGameplayTagsK2Node_MultiCompareBase {
// GameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags
}
