namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("ModelingToolsEditorModeSettings.h")]
public enum EModelingModeAssetGenerationLocation {
	AutoGeneratedWorldRelativeAssetPath=0,
	AutoGeneratedGlobalAssetPath=1,
	CurrentAssetBrowserPathIfAvailable=2,
}
