#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("GeometryCollection/GeometryCollectionDebugDrawActor.h")]
public partial class AGeometryCollectionDebugDrawActor : AActor {
// GeometryCollectionDebugDrawActor
	public FGeometryCollectionDebugDrawWarningMessage WarningMessage_DEPRECATED;
	public FGeometryCollectionDebugDrawActorSelectedRigidBody SelectedRigidBody_DEPRECATED;
	public bool bDebugDrawWholeCollection;
	public bool bDebugDrawHierarchy;
	public bool bDebugDrawClustering;
	public EGeometryCollectionDebugDrawActorHideGeometry HideGeometry;
	public bool bShowRigidBodyId;
	public bool bShowRigidBodyCollision;
	public bool bCollisionAtOrigin;
	public bool bShowRigidBodyTransform;
	public bool bShowRigidBodyInertia;
	public bool bShowRigidBodyVelocity;
	public bool bShowRigidBodyForce;
	public bool bShowRigidBodyInfos;
	public bool bShowTransformIndex;
	public bool bShowTransform;
	public bool bShowParent;
	public bool bShowLevel;
	public bool bShowConnectivityEdges;
	public bool bShowGeometryIndex;
	public bool bShowGeometryTransform;
	public bool bShowBoundingBox;
	public bool bShowFaces;
	public bool bShowFaceIndices;
	public bool bShowFaceNormals;
	public bool bShowSingleFace;
	public int SingleFaceIndex;
	public bool bShowVertices;
	public bool bShowVertexIndices;
	public bool bShowVertexNormals;
	public bool bUseActiveVisualization;
	public float PointThickness;
	public float LineThickness;
	public bool bTextShadow;
	public float TextScale;
	public float NormalScale;
	public float AxisScale;
	public float ArrowScale;
	public FColor RigidBodyIdColor;
	public float RigidBodyTransformScale;
	public FColor RigidBodyCollisionColor;
	public FColor RigidBodyInertiaColor;
	public FColor RigidBodyVelocityColor;
	public FColor RigidBodyForceColor;
	public FColor RigidBodyInfoColor;
	public FColor TransformIndexColor;
	public float TransformScale;
	public FColor LevelColor;
	public FColor ParentColor;
	public float ConnectivityEdgeThickness;
	public FColor GeometryIndexColor;
	public float GeometryTransformScale;
	public FColor BoundingBoxColor;
	public FColor FaceColor;
	public FColor FaceIndexColor;
	public FColor FaceNormalColor;
	public FColor SingleFaceColor;
	public FColor VertexColor;
	public FColor VertexIndexColor;
	public FColor VertexNormalColor;
	public UBillboardComponent SpriteComponent;
}
