#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("EdGraph/EdGraphPin.h")]
public partial class UEdGraphPin_Deprecated : UObject {
	public static UClass StaticClass() {return default;}
	///<summary>Name of this pin</summary>
	public string PinName;
	///<summary>Used as the display name if set</summary>
	public string PinFriendlyName;
	///<summary>The tool-tip describing this pin&#39;s purpose</summary>
	public string PinToolTip;
	///<summary>Direction of flow of this pin (input or output)</summary>
	public EEdGraphPinDirection Direction;
	///<summary>The type of information carried on this pin</summary>
	public FEdGraphPinType PinType;
	///<summary>Default value for this pin (used if the pin has no connections), stored as a string</summary>
	public string DefaultValue;
	///<summary>Initial default value (the autogenerated value, to identify if the user has modified the value), stored as a string</summary>
	public string AutogeneratedDefaultValue;
	///<summary>If the default value for this pin should be an object, we store a pointer to it</summary>
	public UObject DefaultObject;
	///<summary>If the default value for this pin should be an FText, it is stored here.</summary>
	public string DefaultTextValue;
	///<summary>Set of pins that we are linked to</summary>
	public TArray<UEdGraphPin_Deprecated> LinkedTo;
	///<summary>The pins created when a pin is split and hidden</summary>
	public TArray<UEdGraphPin_Deprecated> SubPins;
	///<summary>The pin that was split and generated this pin</summary>
	public UEdGraphPin_Deprecated ParentPin;
	///<summary>Pin that this pin uses for passing through reference connection</summary>
	public UEdGraphPin_Deprecated ReferencePassThroughConnection;
	///<summary>If true, this connector is currently hidden.</summary>
	public bool bHidden;
	///<summary>If true, this connector is unconnectable, and present only to allow the editing of the default text.</summary>
	public bool bNotConnectable;
	///<summary>If true, the default value of this connector is fixed and cannot be modified by the user (it&#39;s visible for reference only)</summary>
	public bool bDefaultValueIsReadOnly;
	///<summary>If true, the default value on this pin is ignored and should not be set</summary>
	public bool bDefaultValueIsIgnored;
	///<summary>If true, the pin may be hidden by user</summary>
	public bool bAdvancedView;
	///<summary>If true, the pin is displayed as ref</summary>
	public bool bDisplayAsMutableRef;
	///<summary>Pin name could be changed, so whenever possible it&#39;s good to have a persistent GUID identifying Pin to reconstruct Node seamlessly</summary>
	public FGuid PersistentGuid;
}
