#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_Postprocess.h")]
public partial struct FDisplayClusterConfigurationViewport_AllNodesColorGrading {
// DisplayClusterConfigurationViewport_AllNodesColorGrading
	public bool bEnableInnerFrustumAllNodesColorGrading;
	public bool bEnableEntireClusterColorGrading;
	public FDisplayClusterConfigurationViewport_ColorGradingRenderingSettings ColorGradingSettings;
}
