namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_Postprocess.h")]
public partial struct FDisplayClusterConfigurationViewport_CustomPostprocess {
	public FDisplayClusterConfigurationViewport_CustomPostprocessSettings Start;
	public FDisplayClusterConfigurationViewport_CustomPostprocessSettings Override;
	public FDisplayClusterConfigurationViewport_CustomPostprocessSettings Final;
}
