#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_Postprocess.h")]
public partial struct FDisplayClusterConfigurationViewport_EntireClusterColorGrading {
// DisplayClusterConfigurationViewport_EntireClusterColorGrading
	public bool bEnableEntireClusterColorGrading;
	public FDisplayClusterConfigurationViewport_ColorGradingRenderingSettings ColorGradingSettings;
}
