#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("DisplayClusterConfigurationTypes_ICVFX.h")]
public partial struct FDisplayClusterConfigurationICVFX_LightcardCustomOCIO {
// DisplayClusterConfigurationICVFX_LightcardCustomOCIO
	public FDisplayClusterConfigurationOCIOConfiguration AllViewportsOCIOConfiguration;
	public TArray<FDisplayClusterConfigurationOCIOProfile> PerViewportOCIOProfiles;
}
