namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Save the images generated by the Movie Graph Pipeline as an 8 bit jpg format. JPEG image files</summary>
[CppInclude("Graph/Nodes/MovieGraphImageSequenceOutputNode.h")]
public partial class UMovieGraphImageSequenceOutputNode_JPG : UMovieGraphImageSequenceOutputNode {
	public static UClass StaticClass() {return default;}
}
