namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Save the images generated by the Movie Graph Pipeline as an 8 bit png format. PNG image files</summary>
[CppInclude("Graph/Nodes/MovieGraphImageSequenceOutputNode.h")]
public partial class UMovieGraphImageSequenceOutputNode_PNG : UMovieGraphImageSequenceOutputNode {
	public static UClass StaticClass() {return default;}
}
