namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Save the images generated by the Movie Graph Pipeline as an lossless 8 bit bmp format. This can</summary>
[CppInclude("Graph/Nodes/MovieGraphImageSequenceOutputNode.h")]
public partial class UMovieGraphImageSequenceOutputNode_BMP : UMovieGraphImageSequenceOutputNode {
	public static UClass StaticClass() {return default;}
}
