#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Settings/ProjectPackagingSettings.h")]
///<summary>Implements the Editor's user settings.</summary>
public partial class UProjectPackagingSettings : UObject {
// ProjectPackagingSettings
	public EProjectPackagingBuild Build;
	public EProjectPackagingBuildConfigurations BuildConfiguration;
	public string BuildTarget;
	public bool FullRebuild;
	public bool ForDistribution;
	public bool IncludeDebugFiles;
	public EProjectPackagingBlueprintNativizationMethod BlueprintNativizationMethod;
	public TArray<FFilePath> NativizeBlueprintAssets;
	public bool bIncludeNativizedAssetsInProjectGeneration;
	public bool bExcludeMonolithicEngineHeadersInNativizedCode;
	public bool UsePakFile;
	public bool bUseIoStore;
	public bool bUseZenStore;
	public bool bMakeBinaryConfig;
	public bool bGenerateChunks;
	public bool bGenerateNoChunks;
	public bool bChunkHardReferencesOnly;
	public bool bForceOneChunkPerFile;
	public long MaxChunkSize;
	public bool bBuildHttpChunkInstallData;
	public FDirectoryPath HttpChunkInstallDataDirectory;
	public EAssetRegistryWritebackMethod WriteBackMetadataToAssetRegistry;
	public bool bCompressed;
	public string PackageCompressionFormat;
	public bool bForceUseProjectCompressionFormatIgnoreHardwareOverride;
	public string PackageAdditionalCompressionOptions;
	public string PackageCompressionMethod;
	public int PackageCompressionLevel_DebugDevelopment;
	public int PackageCompressionLevel_TestShipping;
	public int PackageCompressionLevel_Distribution;
	public int PackageCompressionMinBytesSaved;
	public int PackageCompressionMinPercentSaved;
	public bool bPackageCompressionEnableDDC;
	public int PackageCompressionMinSizeToConsiderDDC;
	public string HttpChunkInstallDataVersion;
	public bool IncludePrerequisites;
	public bool IncludeAppLocalPrerequisites;
	public bool bShareMaterialShaderCode;
	public bool bDeterministicShaderCodeOrder;
	public bool bSharedMaterialNativeLibraries;
	public FDirectoryPath ApplocalPrerequisitesDirectory;
	public bool IncludeCrashReporter;
	public EProjectPackagingInternationalizationPresets InternationalizationPreset;
	public TArray<string> CulturesToStage;
	public TArray<string> LocalizationTargetsToChunk;
	public int LocalizationTargetCatchAllChunkId;
	public bool bCookAll;
	public bool bCookMapsOnly;
	public bool bEncryptIniFiles_DEPRECATED;
	public bool bEncryptPakIndex_DEPRECATED;
	public bool GenerateEarlyDownloaderPakFile_DEPRECATED;
	public bool bSkipEditorContent;
	public bool bSkipMovies;
	public TArray<string> UFSMovies;
	public TArray<string> NonUFSMovies;
	public TArray<string> CompressedChunkWildcard;
	public TArray<string> IniKeyBlacklist;
	public TArray<string> IniKeyDenylist;
	public TArray<string> IniSectionBlacklist;
	public TArray<string> IniSectionDenylist;
	public TArray<string> EarlyDownloaderPakFileFiles_DEPRECATED;
	public TArray<FFilePath> MapsToCook;
	public TArray<FDirectoryPath> DirectoriesToAlwaysCook;
	public TArray<FDirectoryPath> DirectoriesToNeverCook;
	public TArray<FDirectoryPath> TestDirectoriesToNotSearch;
	public TArray<FDirectoryPath> DirectoriesToAlwaysStageAsUFS;
	public TArray<FDirectoryPath> DirectoriesToAlwaysStageAsNonUFS;
	public TArray<FDirectoryPath> DirectoriesToAlwaysStageAsUFSServer;
	public TArray<FDirectoryPath> DirectoriesToAlwaysStageAsNonUFSServer;
	public TArray<FProjectBuildSettings> ProjectCustomBuilds;
	public TArray<FProjectBuildSettings> EngineCustomBuilds;
}
