#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("ContextualAnimTypes.h")]
public enum EContextualAnimIKTargetProvider {
	Autogenerated=0,
	Bone=1,
}
