using CSharpToCpp.Utilities;
using GameFramework;

namespace BlueprintLib;

public class UEdGraphPin : UObject
{
    public FName PinName;
    public Int32 SourceIndex;
    public EEdGraphPinDirection Direction;

    //TODO: PinType, DefaultValue, AutogeneratedDefaultValue, DefaultObject; DefaultTextValue

    /** Set of pins that we are linked to */
    TArray<UEdGraphPin> LinkedTo;

    /** The pin that was split and generated this pin */
    UEdGraphPin ParentPin;

    /** Pin that this pin uses for passing through reference connection */
    UEdGraphPin ReferencePassThroughConnection;

}