#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("NiagaraSystem.h")]
///<summary>A Niagara System contains multiple Niagara Emitters to create various effects.</summary>
public partial class UNiagaraSystem : UFXSystemAsset {
// NiagaraSystem
	public UTexture2D ThumbnailImage;
	public bool bExposeToLibrary_DEPRECATED;
	public ENiagaraScriptLibraryVisibility LibraryVisibility;
	public bool bIsTemplateAsset_DEPRECATED;
	public ENiagaraScriptTemplateSpecification TemplateSpecification;
	public string TemplateAssetDescription;
	public string Category;
	public TArray<UNiagaraScript> ScratchPadScripts;
	public FNiagaraParameterStore EditorOnlyAddedParameters;
	public FNiagaraSystemUpdateContext UpdateContext;
	public bool bCompileForEdit;
	public bool bBakeOutRapidIteration;
	public bool bBakeOutRapidIterationOnCook;
	public bool bCompressAttributes;
	public bool bTrimAttributes;
	public bool bTrimAttributesOnCook;
	public bool bIgnoreParticleReadsForAttributeTrim;
	public bool bDisableDebugSwitches;
	public bool bDisableDebugSwitchesOnCook;
	public TArray<FParameterDefinitionsSubscription> ParameterDefinitionsSubscriptions;
	public bool bSupportLargeWorldCoordinates;
	public bool bOverrideCastShadow;
	public bool bOverrideReceivesDecals;
	public bool bOverrideRenderCustomDepth;
	public bool bOverrideCustomDepthStencilValue;
	public bool bOverrideCustomDepthStencilWriteMask;
	public bool bOverrideTranslucencySortPriority;
	public bool bOverrideTranslucencySortDistanceOffset;
	public bool bCastShadow;
	public bool bReceivesDecals;
	public bool bRenderCustomDepth;
	public bool bDisableExperimentalVM;
	public ERendererStencilMask CustomDepthStencilWriteMask;
	public int CustomDepthStencilValue;
	public int TranslucencySortPriority;
	public float TranslucencySortDistanceOffset;
	public bool bDumpDebugSystemInfo;
	public bool bDumpDebugEmitterInfo;
	public bool bRequireCurrentFrameData;
	public bool bFixedBounds;
	public UNiagaraEffectType EffectType;
	public bool bOverrideScalabilitySettings;
	public bool bOverrideAllowCullingForLocalPlayers;
	public bool bAllowCullingForLocalPlayersOverride;
	public TArray<FNiagaraSystemScalabilityOverride> ScalabilityOverrides_DEPRECATED;
	public FNiagaraSystemScalabilityOverrides SystemScalabilityOverrides;
	public TArray<FNiagaraEmitterHandle> EmitterHandles;
	public TArray<UNiagaraParameterCollectionInstance> ParameterCollectionOverrides;
	public TArray<FNiagaraSystemCompileRequest> ActiveCompilations;
	public UNiagaraScript SystemSpawnScript;
	public UNiagaraScript SystemUpdateScript;
	public FNiagaraSystemCompiledData SystemCompiledData;
	public FNiagaraUserRedirectionParameterStore ExposedParameters;
	public UNiagaraEditorDataBase EditorData;
	public UNiagaraEditorParametersAdapterBase EditorParameters;
	public FBox FixedBounds;
	public bool bAutoDeactivate;
	public bool bDeterminism;
	public int RandomSeed;
	public float WarmupTime;
	public int WarmupTickCount;
	public float WarmupTickDelta;
	public bool bFixedTickDelta;
	public float FixedTickDeltaTime;
	public UNiagaraBakerSettings BakerSettings;
	public UNiagaraBakerSettings BakerGeneratedSettings;
	public bool bHasSystemScriptDIsWithPerInstanceData;
	public bool bNeedsGPUContextInitForDataInterfaces;
	public TArray<string> UserDINamesReadInSystemScripts;
	public TArray<UNiagaraDataChannelDefinitions> ReferencedDataChannelDefinitions;
	public TMap<FGuid,UNiagaraMessageDataBase> MessageKeyToMessageMap;
}
