#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("ModelingToolsEditorModeSettings.h")]
public enum EModelingModeAssetGenerationLocation {
	AutoGeneratedWorldRelativeAssetPath=0,
	AutoGeneratedGlobalAssetPath=1,
	CurrentAssetBrowserPathIfAvailable=2,
}
