#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("ModelingToolsEditorModeSettings.h")]
///<summary>Settings for the Modeling Tools Editor Mode plug-in.</summary>
public partial class UModelingToolsEditorModeSettings : UDeveloperSettings {
// ModelingToolsEditorModeSettings
	public bool bEnableDynamicMeshActors;
	public EModelingModeAssetGenerationLocation AssetGenerationLocation;
	public EModelingModeAssetGenerationBehavior AssetGenerationMode;
	public EModelingModeDefaultMeshObjectType DefaultMeshObjectType;
	public string AutoGeneratedAssetPath;
	public bool bStoreUnsavedLevelAssetsInTopLevelGameFolder;
	public bool bUsePerUserAutogenSubfolder;
	public string AutogenSubfolderUserNameOverride;
	public bool bAppendRandomStringToName;
	public bool bRespectLevelEditorGizmoMode;
	public bool bEnablePersistentSelections;
	public bool bEnableMeshSelections;
	public string RestrictiveModeAutoGeneratedAssetPath;
	public bool bEnableAbsoluteWorldSnapping;
}
