namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Some data of an extension-defined type generated by a Customizable Object Extension</summary>
[CppInclude("MuCO/CustomizableObjectExtensionData.h")]
public partial struct FCustomizableObjectExtensionData {
	public FInstancedStruct Data;
}
