#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Struct type generated by the anim BP compiler. Used for sparse class data and mutable data area.</summary>
[CppInclude("Animation/AnimBlueprintGeneratedClass.h")]
public partial class UAnimBlueprintGeneratedStruct : UScriptStruct {
	public static UClass StaticClass() {return default;}
}
