#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Animation/AnimBlueprintGeneratedClass.h")]
///<summary>Struct type generated by the anim BP compiler. Used for sparse class data and mutable data area.</summary>
public partial class UAnimBlueprintGeneratedStruct : UScriptStruct {
// AnimBlueprintGeneratedStruct
}
