namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("CinePrestreamingRecorderSetting.h")]
public partial class UCinePrestreamingRecorderSetting : UMoviePipelineOutputBase {
	public static UClass StaticClass() {return default;}
	///<summary>* Specifies which directory the generated assets be placed in. Assumed to be relative to the root folder,</summary>
	public FDirectoryPath PackageDirectory;
	///<summary>Enable capture of virtual texture page requests.</summary>
	public bool bVirtualTextures;
	///<summary>Enable capture of nanite requests.</summary>
	public bool bNanite;
	///<summary>Automatically add the generated tracks to the target sequence</summary>
	public bool bModifyTargetSequence;
	///<summary>By default we disable any render features that aren&#39;t needed to generate the prestreaming data. This makes renders significantly faster, but also means that the final image generated by the renderer is unusable.</summary>
	public bool bDisableAdvanceRenderFeatures;
	///<summary>First frame to output in each recorded asset. Frames before this are dropped.</summary>
	public int StartFrame;
	///<summary>Last frame to capture in each recorded asset. Frames after this are dropped. (Set to 0 to ignore).</summary>
	public int EndFrame;
	///<summary>OnGenerateData</summary>
	public FOnCinePrestreamingGenerateData OnGenerateData;
}
