namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Convert a sphere covering, as generated by the &#39;protect negative space&#39; option on the &quot;Generate Cluster Convex Hull&quot; nodes, to a dynamic mesh</summary>
[CppInclude("Dataflow/GeometryCollectionDebugNodes.h")]
public partial struct FSphereCoveringToMeshDataflowNode {
	public FDataflowSphereCovering SphereCovering;
	public int VerticesAlongEachSide;
	public UDynamicMesh Mesh;
}
