#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Engine/EngineBaseTypes.h")]
///<summary>Define view modes to get specific show flag settings (some on, some off and some are not altered)</summary>
public enum EViewModeIndex {
	VMI_BrushWireframe=0,
	VMI_Wireframe=1,
	VMI_Unlit=2,
	VMI_Lit=3,
	VMI_Lit_DetailLighting=4,
	VMI_LightingOnly=5,
	VMI_LightComplexity=6,
	VMI_ShaderComplexity=8,
	VMI_LightmapDensity=9,
	VMI_LitLightmapDensity=10,
	VMI_ReflectionOverride=11,
	VMI_VisualizeBuffer=12,
	VMI_StationaryLightOverlap=14,
	VMI_CollisionPawn=15,
	VMI_CollisionVisibility=16,
	VMI_LODColoration=18,
	VMI_QuadOverdraw=19,
	VMI_PrimitiveDistanceAccuracy=20,
	VMI_MeshUVDensityAccuracy=21,
	VMI_ShaderComplexityWithQuadOverdraw=22,
	VMI_HLODColoration=23,
	VMI_GroupLODColoration=24,
	VMI_MaterialTextureScaleAccuracy=25,
	VMI_RequiredTextureResolution=26,
	VMI_PathTracing=27,
	VMI_RayTracingDebug=28,
	VMI_VisualizeNanite=29,
	VMI_VirtualTexturePendingMips=30,
	VMI_VisualizeLumen=31,
	VMI_VisualizeVirtualShadowMap=32,
	VMI_VisualizeGPUSkinCache=33,
	VMI_VisualizeSubstrate=34,
	VMI_VisualizeGroom=35,
	VMI_Max=36,
	VMI_Unknown=255,
}
