#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("NiagaraShared.h")]
///<summary>Information about a data interface function generated by the translator.</summary>
public partial struct FNiagaraDataInterfaceGeneratedFunction {
// NiagaraDataInterfaceGeneratedFunction
	public TArray<FNiagaraVariableCommonReference> VariadicInputs;
	public TArray<FNiagaraVariableCommonReference> VariadicOutputs;
}
