#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Information about a data interface function generated by the translator.</summary>
[CppInclude("NiagaraShared.h")]
public partial struct FNiagaraDataInterfaceGeneratedFunction {
	public TArray<FNiagaraVariableCommonReference> VariadicInputs;
	public TArray<FNiagaraVariableCommonReference> VariadicOutputs;
}
