#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Formats/JSON426/DisplayClusterConfigurationJsonTypes_426.h")]
public partial struct FDisplayClusterConfigurationJsonClusterSync_426 {
// DisplayClusterConfigurationJsonClusterSync_426
	public FDisplayClusterConfigurationJsonClusterSyncPolicy_426 RenderSyncPolicy;
	public FDisplayClusterConfigurationJsonClusterSyncPolicy_426 InputSyncPolicy;
}
