#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Formats/JSON427/DisplayClusterConfigurationJsonTypes_427.h")]
public partial struct FDisplayClusterConfigurationJsonClusterSync_427 {
// DisplayClusterConfigurationJsonClusterSync_427
	public FDisplayClusterConfigurationJsonClusterSyncPolicy_427 RenderSyncPolicy;
	public FDisplayClusterConfigurationJsonClusterSyncPolicy_427 InputSyncPolicy;
}
