#pragma warning disable CS8618,CS8603,CS1587,CS1591
namespace GameFramework;
using CSharpToCpp.Utilities;
///<summary>Statistics page for shader cooker stats.</summary>
[CppInclude("ShaderCookerStats.h")]
public partial class UShaderCookerStats : UObject {
	public static UClass StaticClass() {return default;}
	///<summary>Material name</summary>
	public string Name;
	///<summary>Material platform</summary>
	public string Platform;
	///<summary>Material Category. Edit Engine/Config/ShaderConfiguration.csv &amp; Engine/Config/ShaderConfiguration.csv to configure</summary>
	public string Category;
	///<summary>Number of shaders that was actually compiled and not present in the DDC</summary>
	public int Compiled;
	///<summary>Total number of shaders cooked</summary>
	public int Cooked;
	///<summary>Number of material permutations generated by switch etc.</summary>
	public int Permutations;
	///<summary>Cpu time spent compiling shaders not in DDC</summary>
	public float CompileTime;
	///<summary>Material path</summary>
	public string Path;
}
